# Generated by Django 6.0.6 on 2026-06-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newspaper_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redactor",
            options={
                "ordering": ["username"],
                "verbose_name": "redactor",
                "verbose_name_plural": "redactors",
            },
        ),
    ]
